# Generated by Django 5.0 on 2024-12-06 08:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_alter_product_options_alter_bulkpricing_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_customers', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('returning_customers', models.PositiveIntegerField(default=0)),
                ('average_session_duration', models.DurationField(blank=True, null=True)),
                ('cart_abandonment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_c_date_342f7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SalesMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='analytics_s_date_8f3cc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opening_stock', models.PositiveIntegerField()),
                ('closing_stock', models.PositiveIntegerField()),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('units_refunded', models.PositiveIntegerField(default=0)),
                ('restock_amount', models.PositiveIntegerField(default=0)),
                ('low_stock_alerts', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-date', 'product'],
                'indexes': [models.Index(fields=['date', 'product'], name='analytics_i_date_0339cb_idx'), models.Index(fields=['product', 'date'], name='analytics_i_product_d0ea2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
                ('add_to_cart_count', models.PositiveIntegerField(default=0)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'ordering': ['-date', '-revenue'],
                'indexes': [models.Index(fields=['date', 'product'], name='analytics_p_date_151cfe_idx'), models.Index(fields=['product', 'date'], name='analytics_p_product_f90fd1_idx')],
            },
        ),
    ]
