# Generated by Django 5.0 on 2024-12-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymetric',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='inventorymetric',
            name='analytics_i_date_0339cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorymetric',
            name='analytics_i_product_d0ea2a_idx',
        ),
        migrations.RemoveField(
            model_name='inventorymetric',
            name='closing_stock',
        ),
        migrations.RemoveField(
            model_name='inventorymetric',
            name='low_stock_alerts',
        ),
        migrations.RemoveField(
            model_name='inventorymetric',
            name='opening_stock',
        ),
        migrations.RemoveField(
            model_name='inventorymetric',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventorymetric',
            name='restock_amount',
        ),
        migrations.RemoveField(
            model_name='inventorymetric',
            name='units_refunded',
        ),
        migrations.RemoveField(
            model_name='inventorymetric',
            name='units_sold',
        ),
        migrations.AddField(
            model_name='inventorymetric',
            name='metrics_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='inventorymetric',
            index=models.Index(fields=['date'], name='analytics_i_date_4241be_idx'),
        ),
    ]
