# Generated by Django 5.0 on 2024-12-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0003_alter_bulkpricing_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='preferred_categories',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_users', to='products.category'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='saved_items',
            field=models.ManyToManyField(blank=True, related_name='saved_by_users', to='products.product'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='wishlist_items',
            field=models.ManyToManyField(blank=True, related_name='in_wishlists', to='products.product'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='email_notifications',
            field=models.CharField(choices=[('all', 'All Notifications'), ('important', 'Important Only'), ('none', 'None')], default='all', max_length=10, verbose_name='email notifications'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='push_notifications',
            field=models.CharField(choices=[('all', 'All Notifications'), ('important', 'Important Only'), ('none', 'None')], default='all', max_length=10, verbose_name='push notifications'),
        ),
    ]
