# Generated by Django 5.0 on 2024-12-06 08:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_delivery_zone_order_pickup_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='checkoutsession',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='max_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('100000000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='min_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('100'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
