# Generated by Django 5.0 on 2024-12-06 19:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_checkoutsession_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ['name'], 'verbose_name': 'payment method', 'verbose_name_plural': 'payment methods'},
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='payment_methods/', verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(Decimal('100000000'))], verbose_name='maximum amount'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='min_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('100'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100'))], verbose_name='minimum amount'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('AIRTEL_MONEY', 'Airtel Money')], max_length=20, verbose_name='provider'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='requires_verification',
            field=models.BooleanField(default=True, verbose_name='requires verification'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
