# Generated by Django 5.0 on 2024-12-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payments', '0002_alter_mobilepayment_order'),
        ('orders', '0002_deliveryzone_remove_customerorder_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerOrder',
        ),
        migrations.DeleteModel(
            name='CustomerOrderItem',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
    ]
