# Generated by Django 5.0 on 2024-12-05 17:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='provider name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='provider code')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('api_base_url', models.URLField(verbose_name='API base URL')),
                ('api_key', models.CharField(max_length=255, verbose_name='API key')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API secret')),
                ('webhook_secret', models.CharField(max_length=255, verbose_name='webhook secret')),
            ],
            options={
                'verbose_name': 'mobile payment provider',
                'verbose_name_plural': 'mobile payment providers',
            },
        ),
        migrations.CreateModel(
            name='MobilePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='UGX', max_length=3, verbose_name='currency')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('provider_tx_id', models.CharField(blank=True, max_length=255, verbose_name='provider transaction ID')),
                ('provider_tx_ref', models.CharField(max_length=255, unique=True, verbose_name='provider transaction reference')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_payments', to='orders.customerorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_payments', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='mobile_payments.mobilepaymentprovider')),
            ],
            options={
                'verbose_name': 'mobile payment',
                'verbose_name_plural': 'mobile payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(max_length=50, verbose_name='notification type')),
                ('status', models.CharField(max_length=50, verbose_name='status')),
                ('raw_payload', models.JSONField(verbose_name='raw payload')),
                ('is_processed', models.BooleanField(default=False, verbose_name='processed')),
                ('processing_errors', models.TextField(blank=True, verbose_name='processing errors')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='received at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='mobile_payments.mobilepayment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='mobile_payments.mobilepaymentprovider')),
            ],
            options={
                'verbose_name': 'payment notification',
                'verbose_name_plural': 'payment notifications',
                'ordering': ['-received_at'],
            },
        ),
    ]
