# Generated by Django 5.0 on 2024-12-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payments', '0001_initial'),
        ('orders', '0002_deliveryzone_remove_customerorder_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilepayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_payments', to='orders.order'),
        ),
    ]
