# Generated by Django 5.0 on 2024-12-06 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payments', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilepayment',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='provider_tx_id',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='provider_tx_ref',
        ),
        migrations.AddField(
            model_name='mobilepayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='provider',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='mobilepayment',
            index=models.Index(fields=['transaction_id'], name='mobile_paym_transac_4d0c54_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilepayment',
            index=models.Index(fields=['status'], name='mobile_paym_status_2c3df1_idx'),
        ),
        migrations.AddIndex(
            model_name='mobilepayment',
            index=models.Index(fields=['created_at'], name='mobile_paym_created_91e1c1_idx'),
        ),
    ]
