# Generated by Django 5.0 on 2024-12-06 19:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_payments', '0003_mobilepayment_currency_alter_mobilepayment_amount_and_more'),
        ('orders', '0002_alter_deliveryzone_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilepayment',
            options={'ordering': ['-created_at'], 'verbose_name': 'mobile payment', 'verbose_name_plural': 'mobile payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'payment notification', 'verbose_name_plural': 'payment notifications'},
        ),
        migrations.RemoveIndex(
            model_name='mobilepayment',
            name='mobile_paym_transac_4d0c54_idx',
        ),
        migrations.RemoveIndex(
            model_name='mobilepayment',
            name='mobile_paym_status_2c3df1_idx',
        ),
        migrations.RemoveIndex(
            model_name='mobilepayment',
            name='mobile_paym_created_91e1c1_idx',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='processing_errors',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='raw_payload',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='received_at',
        ),
        migrations.RemoveField(
            model_name='paymentnotification',
            name='status',
        ),
        migrations.AddField(
            model_name='mobilepayment',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='provider reference'),
        ),
        migrations.AddField(
            model_name='mobilepayment',
            name='provider_response',
            field=models.JSONField(blank=True, null=True, verbose_name='provider response'),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='payload',
            field=models.JSONField(default=dict, verbose_name='notification payload'),
        ),
        migrations.AddField(
            model_name='paymentnotification',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='processed'),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('100')), django.core.validators.MaxValueValidator(Decimal('100000000'))]),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobile_payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_payments.mobilepaymentprovider'),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='transaction ID'),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='mobilepaymentprovider',
            name='code',
            field=models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money')], max_length=10, unique=True, verbose_name='provider code'),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentnotification',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobile_payments.mobilepaymentprovider'),
        ),
    ]
