# Generated by Django 5.0 on 2024-12-05 19:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productoption_bundleitem_productbundle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpricing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('-999999.99')), django.core.validators.MaxValueValidator(Decimal('999999.99'))]),
        ),
    ]
