# Generated by Django 5.0 on 2024-12-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage_productreview'),
        ('products', '0003_inventory_models'),
    ]

    operations = [
    ]
