# Generated by Django 5.0 on 2024-12-06 08:10

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_bulkpricing_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='bulkpricing',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100')), django.core.validators.MaxValueValidator(Decimal('100000000'))]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('-999999999')), django.core.validators.MaxValueValidator(Decimal('999999999'))]),
        ),
    ]
