# Generated by Django 5.0 on 2024-12-05 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20241205_1842'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reviewvote',
            new_name='products_re_review__1abb32_idx',
            old_name='products_re_review__0a4e7b_idx',
        ),
        migrations.RenameIndex(
            model_name='stockadjustment',
            new_name='products_st_invento_d05f9e_idx',
            old_name='products_st_invento_823cf2_idx',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['product', 'status', 'created_at'], name='products_pr_product_c8d510_idx'),
        ),
        migrations.AddIndex(
            model_name='productreview',
            index=models.Index(fields=['user', 'created_at'], name='products_pr_user_id_f49ca3_idx'),
        ),
    ]
