# Generated by Django 5.0 on 2024-12-06 17:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('similar', 'Similar Products'), ('frequently_bought', 'Frequently Bought Together'), ('personalized', 'Personalized Recommendation')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_recommendations', to='products.product')),
                ('source_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_recommendations', to='products.product')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('source_product', 'recommended_product', 'recommendation_type')},
            },
        ),
    ]
